datasets:
    mesh_folder:
        data_folder: '.datasets/HuGe100K/batch1/flux_batch1' # 'meshes/smplx'
    num_workers: 4
deformation_transfer_path: 'transfer_data/smplx2smpl_deftrafo_setup.pkl'
mask_ids_fname: ''
summary_steps: 100
batch_size: 10

edge_fitting:
    per_part: False

optim:
    type: 'lbfgs'
    maxiters: 100
    gtol: 1e-04

use_cuda: true
output_folder: '.datasets/HuGe100K/'
body_model:
    model_type: "smpl"
    gender: "neutral"
    ext: 'pkl'
    folder: ".datasets/body_models/models"
    use_compressed: False
    use_face_contour: True
    smpl:
        betas:
            num: 10
